# Generated by Django 6.0.2 on 2026-02-21 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('attendance', models.FloatField()),
                ('internal_marks', models.FloatField()),
                ('assignment_marks', models.FloatField()),
                ('study_hours', models.FloatField()),
            ],
        ),
    ]
